name: Podcast
description: A Flutter Podcast App

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  device_preview: ^0.4.5
  basics: ^0.4.0+1
  assets_audio_player:
    git:
      url: git://github.com/preetjdp/Flutter-AssetsAudioPlayer.git
      ref: Add-Is-Buffering
  provider: ^4.1.3
  dio: ^3.0.9
  equatable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^3.0.6

flutter:
  uses-material-design: true

  fonts:
    - family: Aileron
      fonts:
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
        - asset: assets/fonts/Aileron/Aileron-UltraLight.otf
          weight: 100
        - asset: assets/fonts/Aileron/Aileron-Thin.otf
          weight: 200
        - asset: assets/fonts/Aileron/Aileron-Light.otf
          weight: 300
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 400
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 500
        - asset: assets/fonts/Aileron/Aileron-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Aileron/Aileron-Bold.otf
          weight: 700
        - asset: assets/fonts/Aileron/Aileron-Heavy.otf
          weight: 800
        - asset: assets/fonts/Aileron/Aileron-Black.otf
          weight: 900
        - asset: assets/fonts/Aileron/Aileron-UltraLightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-ThinItalic.otf
        - asset: assets/fonts/Aileron/Aileron-SemiBoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-LightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-HeavyItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BlackItalic.otf
