name: Podcast
description: A Flutter Podcast App

publish_to: "none"

version: 0.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #[Standard Structure Basics] Start
  basics: ^0.4.0+1
  after_layout: ^1.0.7+2
  cupertino_icons: ^1.0.2
  retry: ^3.0.1
  device_preview:
    git:
      url: git://github.com/josh-burton/flutter_device_preview.git
      ref: mediaquery-nullok
      path: device_preview/
    
  flutter_launcher_icons: ^0.8.1
  #[Standard Structure Basics] End
  #[Standard Structure State] Start
  rxdart: ^0.25.0
  state_notifier: ^0.7.0
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.11.0
  #[Standard Structure State] End
  assets_audio_player: ^2.0.10
  dio: ^3.0.10
  equatable: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.1

dependency_overrides:
  shared_preferences: ^0.5.12

flutter:
  uses-material-design: true

  fonts:
    - family: Aileron
      fonts:
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
        - asset: assets/fonts/Aileron/Aileron-UltraLight.otf
          weight: 100
        - asset: assets/fonts/Aileron/Aileron-Thin.otf
          weight: 200
        - asset: assets/fonts/Aileron/Aileron-Light.otf
          weight: 300
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 400
        - asset: assets/fonts/Aileron/Aileron-Regular.otf
          weight: 500
        - asset: assets/fonts/Aileron/Aileron-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Aileron/Aileron-Bold.otf
          weight: 700
        - asset: assets/fonts/Aileron/Aileron-Heavy.otf
          weight: 800
        - asset: assets/fonts/Aileron/Aileron-Black.otf
          weight: 900
        - asset: assets/fonts/Aileron/Aileron-UltraLightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-ThinItalic.otf
        - asset: assets/fonts/Aileron/Aileron-SemiBoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-LightItalic.otf
        - asset: assets/fonts/Aileron/Aileron-HeavyItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BoldItalic.otf
        - asset: assets/fonts/Aileron/Aileron-BlackItalic.otf
